service: frontend

plugins:
  - serverless-s3-sync
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  region: ${opt:region, '${env:TARGET_REGION}'}

custom: ${file(./custom.yml.js)}

resources:
  Resources: ${file(./sls-resources.yml.js)}
