service: slic-starter-backend

plugins:
  # Order of plugins is important for dynamodb-local
  # Using fork of serverless-dynamodb-local due to https://github.com/99xt/dynamodb-localhost/issues/25
  - '@dathuis/serverless-dynamodb-local'
  - serverless-offline
  - serverless-prune-plugin
  - serverless-log-forwarding
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: ${self:custom.runtime}
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  tracing: true
  iamRoleStatements: ${file(./sls-iam-role-statements.yml)}

custom: ${file(./custom.yml)}

functions: ${file(./sls-functions.yml)}

resources:
  Outputs:
    userPool:
      Value: !Ref slicUserPool
      Export:
        Name: ${self:provider.stage}-user-pool-id
    userPoolClient:
      Value: !Ref slicUserPoolClient
      Export:
        Name: ${self:provider.stage}-user-pool-client-id
    identityPool:
      Value: !Ref slicIdentityPool
      Export:
        Name: ${self:provider.stage}-identity-pool

  Resources: ${file(./sls-resources.yml)}
