service: api-service
provider:
  name: aws
  runtime: ${self:custom.runtime}
  region: ${self:custom.region}
  stage: ${self:custom.stage}
custom: ${file(./custom.yml)}
resources:
  Resources:
    apiCustomDomain:
      Type: AWS::ApiGateway::DomainName
      Properties:
        CertificateArn: ${self:custom.apiConfig.apiCert}
        DomainName: ${self:custom.apiDomainName}

    apiDomainDns:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId: ${self:custom.apiConfig.publicHostedZone}
        RecordSets:
          - Name: ${self:custom.apiDomainName}
            Type: A
            AliasTarget:
              DNSName: !GetAtt apiCustomDomain.DistributionDomainName
              HostedZoneId: ${self:custom.cloudFrontHostedZoneId}
          - Name: ${self:custom.apiDomainName}
            Type: AAAA
            AliasTarget:
              DNSName: !GetAtt apiCustomDomain.DistributionDomainName
              HostedZoneId: ${self:custom.cloudFrontHostedZoneId}
  Outputs:
    ApiDistributionDomainName:
      Value: !GetAtt apiCustomDomain.DistributionDomainName
      Export:
        Name: ${self:provider.stage}-api-distribution-domain-name
