service: logging-service

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: python2.7
  stage: ${self:custom.stage}
  region: ${self:custom.region}
# iamRoleStatements: ${file(./sls-iam-role-statements.yml)}

custom: ${file(./custom.yml)}

functions: ${file(./sls-functions.yml)}

resources:
  Outputs:
    loggingFunctionArn:
      Value: !GetAtt LambdaUnderscorehandlerLambdaFunction.Arn
      Export:
        Name: ${self:provider.stage}-log-forwarder-function-arn
