service: logging-service 

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
# iamRoleStatements: ${file(./sls-iam-role-statements.yml)}

custom: ${file(./custom.yml)}

#functions: ${file(./sls-functions.yml)}

resources: 
  Resources: ${file(./sls-resources.yml)}
  Transform: AWS::Serverless-2016-10-31
