service: logging-service

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: ${self:custom.runtime}
  tracing: true
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  iamRoleStatements: ${file(./sls-iam-role-statements.yml)}

custom: ${file(./custom.yml)}

functions: ${file(./sls-functions.yml)}

resources:
  Outputs:
    loggingFunctionArn:
      Value: !GetAtt LogForwarderLambdaFunction.Arn
      Export:
        Name: ${self:provider.stage}-log-forwarder-function-arn
