service: logging-service

plugins:
  - serverless-pseudo-parameters

custom:
  logBucketName: slic-lists-logs-${self:provider.stage}

provider:
  name: aws
  stage: ${opt:stage, 'local'}
  region: ${opt:region, '${env:TARGET_REGION}'}
  runtime: nodejs10.x
  stackTags:
    LOGS_EXCLUDE: 'true'
    SLIC_STAGE: ${self:provider.stage}

functions:
  logProcessor:
    handler: src/log-processor.process
    timeout: 60

resources:
  Transform: AWS::Serverless-2016-10-31
  Resources: ${file(./sls-resources.yml)}
