service: sharing-service

plugins:
  - '@dathuis/serverless-dynamodb-local'
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: ${self:custom.runtime}
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  tracing: true
  iamRoleStatements: ${file(./sls-iam-role-statements.yml)}
  resourcePolicy:
    - Effect: Allow
      Principal: '*'
      Action: 'execute-api:Invoke'
      Resource:
        - execute-api:/*/*/*

custom: ${file(./custom.yml)}

functions: ${file(./sls-functions.yml)}

resources:
  Resources: ${file(./sls-resources.yml)}

