cognitoAuthorizer:
  Type: AWS::ApiGateway::Authorizer
  Properties:
    IdentitySource: method.request.header.Authorization
    Name: slic-user-pool-authorizer-sharing-service
    RestApiId:
      Ref: ApiGatewayRestApi
    Type: COGNITO_USER_POOLS
    ProviderARNs:
      - ${ssm:UserPoolArn}

# Workaround for "Invalid stage identifier specified"
# See https://github.com/serverless/serverless/issues/4029
resApiGatewayDeployment:
  Type: AWS::ApiGateway::Deployment
  DependsOn: ApiGatewayMethodConfirmCodeVarPost
  Properties:
    StageName: ${self:provider.stage}
    RestApiId:
      Ref: ApiGatewayRestApi

apiCustomDomainPathMappings:
  Type: AWS::ApiGateway::BasePathMapping
  Properties:
    BasePath: 'share'
    RestApiId:
      Ref: ApiGatewayRestApi
    DomainName: ${self:custom.apiDomainName}
    Stage: ${self:provider.stage}
  DependsOn: resApiGatewayDeployment
