service: slic-starter-user-service

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: ${self:custom.runtime}
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  iamRoleStatements: ${file(./sls-iam-role-statements.yml)}
  resourcePolicy:
    - Effect: Allow
      Principal:
        AWS: 'arn:aws:iam::#{AWS::AccountId}:root'
      Action: 'execute-api:Invoke'
      Resource:
        - execute-api:/*/*/*
  logs:
    restApi: true

custom: ${file(./custom.yml)}

functions: ${file(./sls-functions.yml)}

resources:
  Resources: ${file(./sls-resources.yml)}
