userServiceNameParameter:
  Type: AWS::SSM::Parameter
  Properties:
    Name: UserServiceUrl
    Type: String
    Value:
      Fn::Join:
        - ''
        - - 'https://'
          - !Ref ApiGatewayRestApi
          - '.execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}/user/'
