service: checklist-service

plugins:
  # Order of plugins is important for dynamodb-local
  # Using fork of serverless-dynamodb-local due to https://github.com/99xt/dynamodb-localhost/issues/25
  - '@dathuis/serverless-dynamodb-local'
  - serverless-offline
  - serverless-prune-plugin
  - serverless-log-forwarding
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: ${self:custom.runtime}
  stage: ${self:custom.stage}
  tracing:
    apiGateway: true
    lambda: true
  region: ${self:custom.region}
  iamRoleStatements: ${file(./sls-iam-role-statements.yml)}

custom: ${file(./custom.yml)}

functions: ${file(./sls-functions.yml)}

resources:
  Resources: ${file(./sls-resources.yml)}
