rervice: checklist-service

plugins:
  # Order of plugins is important for dynamodb-local
  # Using fork of serverless-dynamodb-local due to https://github.com/99xt/dynamodb-localhost/issues/25
  - '@dathuis/serverless-dynamodb-local'
  - serverless-offline
  - serverless-prune-plugin
  - serverless-log-forwarding
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  region: ${opt:region, '${self:custom.defaultRegions.${self:provider.stage}}'}
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements: ${file(./sls-iam-role-statements.yml)}
  environment:
    SLIC_STAGE: ${self:provider.stage}
    CHECKLIST_TABLE_NAME: ${self:custom.checklistTableName}

custom:
<<<<<<< HEAD
  checklistTableName: ${self:provider.stage}Checklists
  nsDomain: ${env:SLIC_NS_DOMAIN}
  domainPrefixes: ${file(../common-config.json):domainPrefixes}
  apiDomainName: api.${self:custom.domainPrefixes.${self:provider.stage}}${self:custom.nsDomain}
  serverless-offline:
    port: 4000
    stage: local
    region: ${self:custom.defaultRegions.${self:provider.stage}}
  dynamodb:
    start:
      migrate: true
  prune:
    automatic: true
    number: 3
  logForwarding:
    destinationARN: !ImportValue ${self:provider.stage}-log-forwarder-function-arn

functions: ${file(./sls-functions.yml)}

resources:
  Resources: ${file(./sls-resources.yml)}
