service: welcome-service

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-pseudo-parameters
  - serverless-log-forwarding

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  region: ${opt:region, '${self:custom.defaultRegions.${self:provider.stage}}'}
  tracing:
    lambda: true
  iamRoleStatements: ${file(./sls-iam-role-statements.yml)}
  environment:
    SLIC_STAGE: ${self:provider.stage}

custom:
  emailQueueName: ${self:custom.stage}-email-queue
  prune:
    automatic: true
    number: 3
  serverless-offline:
    port: 4001
    stage: local
    region: ${self:custom.defaultRegions.${self:provider.stage}}
  logForwarding:
    destinationARN: !ImportValue ${self:provider.stage}-log-forwarder-function-arn

functions: ${file(./sls-functions.yml)}
