service: welcome-service

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-pseudo-parameters
  - serverless-log-forwarding
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, '${env:TARGET_REGION}'}
  tracing:
    lambda: true
  environment:
    SLIC_STAGE: ${self:provider.stage}

custom:
  emailQueueName: ${self:provider.stage}-email-queue
  prune:
    automatic: true
    number: 3
  serverless-offline:
    port: 4001
    stage: local
    region: ${self:provider.region}
  logForwarding:
    destinationARN: !ImportValue ${self:provider.stage}-log-forwarder-function-arn

functions: ${file(./sls-functions.yml)}
